//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG
    {
        public DONDATHANG()
        {
            this.CHITIETDONDATHANGs = new HashSet<CHITIETDONDATHANG>();
        }
    
        public int MaDonHang { get; set; }
        public bool DaThanhToan { get; set; }
        public decimal TriGia { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public int MaKH { get; set; }
    
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
