//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public SACH()
        {
            this.CHITIETDONDATHANGs = new HashSet<CHITIETDONDATHANG>();
            this.MoTas = new HashSet<MoTa>();
            this.VIETSACHes = new HashSet<VIETSACH>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public decimal GiaBan { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int SoLuongTon { get; set; }
        public int MaCD { get; set; }
        public int MaNXB { get; set; }
        public int MaTG { get; set; }
        public Nullable<int> tmp { get; set; }
    
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual ICollection<MoTa> MoTas { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual ICollection<VIETSACH> VIETSACHes { get; set; }
    }
}
